name: Build and upload

on:
  pull_request: {}
  push:
    branches:
      - '*'
    tags:
      - '*'

# Must set Settings -> Actions -> General -> Workflow permissions to
# "Read and write permissions"
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # For git describe

      - name: Install clickable
        run: pip3 install --user --upgrade clickable-ut

      - name: Build
        run: clickable build --output .

      - name: Generate variables
        id: filename
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          GIT_VERSION="$(git describe --tags --always)"
          echo "version=$GIT_VERSION" >> $GITHUB_OUTPUT
          echo "zipname=annotate-$GIT_VERSION" >> $GITHUB_OUTPUT

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.filename.outputs.zipname }}
          path: annotate.semphris_*.click

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.filename.outputs.version }}
          files: annotate.semphris_*.click
          draft: true
