name: Build and upload

on:
  pull_request: {}
  push:
    branches:
      - '*'
    tags:
      - '*'

# Must set Settings -> Actions -> General -> Workflow permissions to
# "Read and write permissions"
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # For git describe

      - name: Install clickable
        run: pip3 install --user --upgrade clickable-ut

      - name: Build
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          clickable build --arch amd64 --output .
          clickable build --arch arm64 --output .
          clickable build --arch armhf --output .

      - name: Generate variables
        id: filename
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          echo "version=$(git describe --tags --always)" >> $GITHUB_OUTPUT

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          path: annotate.semphris_*.click

      - name: Upload to the OpenStore
        if: startsWith(github.ref, 'refs/tags/')
        env:
          OPENSTORE_API_KEY: ${{ secrets.OPENSTORE_API_KEY }}
        shell: bash
        run: |
          clickable publish -a amd64 -- "$(git tag -l "$(git describe --tags --exact-match)" --format='%(contents)')"
          clickable publish -a arm64
          clickable publish -a armhf

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.filename.outputs.version }}
          files: annotate.semphris_*.click
          draft: true
